#!/usr/bin/env Rscript
"Takes a directory of TSVs generated by make_model_results_tsv.py and will generate model
performance statistics, including accuracy, per-step prec, recall, f1, and confusion
matrices, both per-video and across all videos.

Usage: model_metrics.R [-h] [-c -W WIDTH -H HEIGHT -E IMGEXT] -o OUTDIR -f FACTORS TSVDIR

Options:
	-h             Print this menu and exit.
	-c             Flag to indicate you want confusion matrices generated
	-W WIDTH       Width of output plots in cm [default: 12].
	-H WIDTH       Width of output plots in cm [default: 8].
	-E IMGEXT      File-format for image extension [default: png].
	-f FACTORS     CSV file that holds short to long name map and ordered in user preferences that save files will keep (eg temporally)
	-o OUTDIR      Directory (already created) in which to place the results

Arguments:
	TSVDIR         Directory full of TSVs on model results per video. TSVS need, at minimum, columns (vid_name, gt, predicted)
" -> doc

library(docopt)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(caret))


calculate_metrics <- function(df) {
  metrics <- confusionMatrix(data = df$predicted, reference = df$gt, mode = "prec_recall")

  # generate a raw table of all the info
  raw_metrics <- metrics %>% broom::tidy(by_class = TRUE)

  # generate metrics table from precision, recall, f1, prevalence stored in $byClass
  # this is similar to the table I used in the POEM paper
  perclass_metrics <- metrics$byClass %>%
    as_tibble(rownames = "Phase") %>%
    select(Phase, Precision, Recall, F1, Prevalence) %>%
    # clean-up phase name to remove antecedent Class:\s
    mutate(Phase = str_remove(Phase, "^Class\\:\\s+")) %>%
    # calculate overall metrics for prevalence unweighted and weighted averages
    bind_rows(
      summarise(.,
        Phase = "Overall (Unweighted)", Precision = mean(Precision),
        Recall = mean(Recall), F1 = mean(F1)
      ),
      summarise(.,
        Phase = "Overall (Weighted)", Precision = sum(Precision * Prevalence),
        Recall = sum(Recall * Prevalence), F1 = sum(F1 * Prevalence)
      )
    )
  # generate a tidy-table from which to create confusion matrix plots
  confusion_table <- metrics$table %>%
    as_tibble() %>%
    # fix up names to correlate to their use elsewhere
    transmute(prediction = Prediction, gt = Reference, n = n) %>%
    # add "recall confusion matrix stats" (aka for each ground truth, what proportion
    # was predicted as each possible category
    group_by(gt) %>%
    mutate(recall_prop = n / sum(n)) %>%
    # add "precision confusion matrix stats" (aka for each predicted phase, what proportion
    # was each ground truth
    group_by(prediction) %>%
    mutate(precision_prop = n / sum(n)) %>%
    # make it a plain ungrouped tibble (otherwise future steps will get messed up)
    ungroup()

  # return all the info as a named vector
  list(
    raw = raw_metrics,
    perclass = perclass_metrics,
    confusion = confusion_table
  )
}

prettify <- function(df, factor_file) {
  phase_col_names <- c("class", "prediction", "gt", "Phase")
  phase_levels <- get_levels_with_overall(factor_file)
  phase_translation <- make_phase_translation(factor_file)

  df %>%
    # now that we've done all calculations, put all dbl columns to 3 sig figs
    mutate_if(is_double, round, digits = 3) %>%
    # change cols that hold phase labels to factors
    mutate_at(vars(any_of(phase_col_names)), parse_factor, levels = phase_levels) %>%
    # makes names long-form
    mutate_at(vars(any_of(phase_col_names)), fct_recode, !!!phase_translation)
}


make_phase_translation <- function(factor_file) {
  # csv structure nicely allows us to create a map (named vector in R) with deframe()
  # fct_recode will later want this in full_name, name order so flip the columns around
  # with select
  read_csv(factor_file, col_types = "cc") %>%
    select(full_name, name) %>%
    # add a phase unweight overall in the name mapping
    add_row(full_name = "Overall (Unweighted)", name = "Overall (Unweighted)") %>%
    # add overall weighted in the name mapping
    add_row(full_name = "Overall (Weighted)", name = "Overall (Weighted)") %>%
    deframe()
}


get_levels_with_overall <- function(factor_file) {
  # Factor info has the correct order of the phases already (user entered
  # them in the csv file in the correct order. Add a level "Idle" which will
  # replace NA in the non-annotated seconds
  read_csv(factor_file, col_types = "cc") %>%
    .[["name"]] %>%
    c(., "Overall (Unweighted)", "Overall (Weighted)")
}


get_levels <- function(factor_file) {
  # Factor info has the correct order of the phases already (user entered
  # them in the csv file in the correct order. Add a level "Idle" which will
  # replace NA in the non-annotated seconds
  read_csv(factor_file, col_types = "cc") %>%
    .[["name"]]
}


get_video_results <- function(tsv_dir, factor_file) {
  phase_levels <- get_levels(factor_file)
  # all videos in format video_NN.tsv with header:
  # (second, vid_num, block, gt, predicted, step_01, ..., step_NN)
  dir(path = tsv_dir, pattern = "^video_\\d{2}.tsv$", full.names = TRUE) %>%
    map(read_tsv, col_types = cols(
      second = col_integer(),
      vid_num = col_integer(),
      block = col_integer(),
      gt = col_character(),
      predicted = col_character(),
      .default = col_double()
    )) %>%
    map(mutate_at, vars(gt, predicted), parse_factor, levels = phase_levels)
}

save_confusion_plot <- function(conf_plot, save_file, save_path, plot_width, plot_height) {
  ggsave(save_file, plot = conf_plot, width = plot_width, height = plot_height, units = c("cm"), path = save_path)
}

save_results <- function(df, df_name, vid_name, results_directory) {
  df %>%
    write_tsv(file.path(results_directory, str_c(vid_name, "_", df_name, ".tsv")), col_names = TRUE)
}


generate_results <- function(df, factor_file, vid_name, results_dir) {
  calculate_metrics(df) %>%
    # make tables pretty
    map(prettify, factor_file) %>%
    # save tables
    walk2(attributes(.)$names, save_results, vid_name, results_dir)
}

plot_confusion <- function(df, prop_col) {
  df %>%
    # flip ground truth order so that first step appears at the top of the y axis
    mutate(gt = fct_rev(gt)) %>%
    ggplot(mapping = aes(x = prediction, y = gt)) +
    # black R programming magic to allow us to specify column in the function see vignette(programming)
    geom_tile(mapping = aes(fill = !!enquo(prop_col))) +
    coord_equal() +
    scale_fill_gradient(name = "Proportion\n", low = "white", high = "#000099", limits = c(0, 1)) +
    labs(
      x = "\nIdentified Phase",
      y = "Ground Truth\n"
    ) +
    theme_classic() +
    theme(
      axis.text.x = element_text(angle = 30, hjust = 1),
      axis.ticks = element_blank(),
      axis.line = element_blank()
    )
}


main <- function(tsv_dir, factor_file, results_dir, wants_conf, conf_width, conf_height, conf_ext) {
  vid_results <- get_video_results(tsv_dir, factor_file)
  # calculate/save stats for each video
  vid_stats <- vid_results %>%
    map2(
      seq_along(.),
      # use seq_along to give us sequence of numbers and str_pad to create names like
      # video_00, video_01,... video_NN
      ~ generate_results(.x, factor_file, str_c("video_", str_pad(.y, 2, side = c("left"), pad = "0")), results_dir)
    )

  # calculate/save stats for overall
  combined_stats <- bind_rows(vid_results) %>%
    generate_results(factor_file, "combined", results_dir)

  if (wants_conf) {
    # plot and map recall confusion matrix for each video
    vid_stats %>%
      # only iterate over confusion tables
      map(pluck, "confusion") %>%
      # plot for "recall" (proportion of ground truth classified as each phase
      map(plot_confusion, recall_prop) %>%
      # generate name as video_NN_recall.conf_ext
      map2(
        seq_along(.),
        ~ save_confusion_plot(
          .x, str_c("video_", str_pad(.y, 2, side = c("left"), pad = "0"), "_recall.", conf_ext),
          results_dir, conf_width, conf_height
        )
      )
    # plot and map precision confusion matrix for each video
    vid_stats %>%
      # only iterate over confusion tables
      map(pluck, "confusion") %>%
      # plot for "precision" (proportion of classified phases for each ground truth
      map(plot_confusion, precision_prop) %>%
      # generate name as video_NN_precision.conf_ext
      map2(
        seq_along(.),
        ~ save_confusion_plot(
          .x, str_c("video_", str_pad(.y, 2, side = c("left"), pad = "0"), "_precision.", conf_ext),
          results_dir, conf_width, conf_height
        )
      )

    # plot and save combined confusion matrices for recall and precision
    combined_stats$confusion %>%
      plot_confusion(recall_prop) %>%
      save_confusion_plot(str_c("combined_recall.", conf_ext), results_dir, conf_width, conf_height)
    combined_stats$confusion %>%
      plot_confusion(precision_prop) %>%
      save_confusion_plot(str_c("combined_precision.", conf_ext), results_dir, conf_width, conf_height)
  }
}

opt <- docopt(doc)
main(opt$TSVDIR, opt$f, opt$o, opt$c, as.numeric(opt$W), as.numeric(opt$H), opt$E)
